steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -f
    - ./.circleci/Dockerfile
    - --tag=gcr.io/${PROJECT_ID}/${_REPO_NAME}:${_TAG_NAME}
    - .
images:
  - gcr.io/${PROJECT_ID}/${_REPO_NAME}:${_TAG_NAME}
